tests: clean legacy
ceph/ceph-ansible pull request #5743
Opened 2020-09-08 08:03 UTC by guits

dnm/wip

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-09-08 08:05 UTC, guits commented
jenkins test centos-non_container-lvm_batch

2020-09-08 08:05 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-08 08:05 UTC, guits commented
jenkins test centos-non_container-all_in_one

2020-09-08 08:06 UTC, guits commented
jenkins test centos-non_container-all_in_one

2020-09-08 08:06 UTC, guits commented
jenkins test centos-container-all_in_one

2020-09-08 08:06 UTC, guits commented
jenkins test centos-container-collocation

2020-09-08 08:06 UTC, guits commented
jenkins test centos-container-external_clients

2020-09-08 08:06 UTC, guits commented
jenkins test centos-container-ooo_collocation

2020-09-08 08:41 UTC, guits commented
jenkins test centos-container-purge

2020-09-08 14:43 UTC, dsavineau requested changes

2020-09-08 14:43 UTC, dsavineau commented on tests/functional/all_daemons/group_vars/all
> +ceph_docker_image_tag: latest-octopus
latest-master

2020-09-08 15:44 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-09-08 16:07 UTC, guits commented
jenkins test centos-container-collocation

2020-09-08 16:07 UTC, guits commented
jenkins test centos-non_container-all_in_one

2020-09-08 16:07 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-08 16:25 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-09 07:08 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2020-09-09 07:09 UTC, guits commented
jenkins test centos-container-update

2020-09-09 07:09 UTC, guits commented
jenkins test centos-non_container-purge

2020-09-09 07:09 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-09 08:28 UTC, guits commented
jenkins test centos-container-update

2020-09-09 08:28 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-09 08:28 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2020-09-09 09:14 UTC, guits commented
jenkins test centos-container-update

2020-09-09 09:14 UTC, guits commented
jenkins test centos-non_container-collocation

2020-09-09 09:14 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2020-09-09 12:41 UTC, guits commented
unrelated failuers

2020-09-09 12:42 UTC, merged