[skip ci] purge: remove potential socket leftovear
ceph/ceph-ansible pull request #5769
Opened 2020-09-11 15:35 UTC by guits

This commit ensure we remove any socket left by ceph and the
`ceph-osd-run.sh` script.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1861755

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-09-11 15:35 UTC, guits commented
jenkins test centos-container-purge

2020-09-11 15:35 UTC, guits commented
jenkins test centos-non_container-purge

2020-09-11 17:40 UTC, dsavineau requested changes

2020-09-14 08:28 UTC, guits commented on infrastructure-playbooks/purge-container-cluster.yml
> +      - /usr/share/ceph-osd-run.sh
not sure whether a lot of people already started to upgrade to octopus. There are some chances this file can be present. I think it doesn't hurt anyway.

What do you think?

2020-09-14 13:23 UTC, dsavineau commented on infrastructure-playbooks/purge-container-cluster.yml
> +      - /usr/share/ceph-osd-run.sh
agreed ! so let's just be sure we have `ceph_osd_docker_run_script_path`

2020-09-14 13:23 UTC, dsavineau approved these changes

2020-09-14 18:26 UTC, dsavineau commented
jenkins test centos-non_container-purge

2020-09-14 18:26 UTC, dsavineau commented
jenkins test centos-container-purge

2020-09-14 19:34 UTC, merged