[skip ci] rgw: fix multi instances scaleout in baremetal
ceph/ceph-ansible pull request #5822
Opened 2020-09-23 15:51 UTC by guits

When rgw and osd are collocated, the current workflow prevents from
scaling out the radosgw_num_instances parameter when rerunning the
playbook in baremetal deployments.

When ceph-osd notifies handlers, it means rgw handlers are triggered
too. The issue with this is that they are triggered before the role
ceph-rgw is run.
In the case a scaleout operation is expected on `radosgw_num_instances`
it causes an issue because keyrings haven't been created yet so the new
instances won't start.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1881313

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-09-23 15:55 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-09-23 15:55 UTC, guits commented
jenkins test centos-container-all_daemons

2020-09-23 16:03 UTC, dsavineau approved these changes

2020-09-24 18:00 UTC, dsavineau commented
jenkins test centos-non_container-all_daemons

2020-09-24 18:00 UTC, dsavineau commented
jenkins test centos-non_container-collocation

2020-09-25 15:27 UTC, dsavineau commented
jenkins test centos-non_container-all_daemons

2020-09-25 15:27 UTC, dsavineau commented
jenkins test centos-non_container-collocation

2020-09-29 13:40 UTC, dsavineau approved these changes

2020-10-01 15:16 UTC, guits commented
jenkins test centos-non_container-collocation

2020-10-01 15:17 UTC, guits commented
jenkins test centos-container-collocation

2020-10-01 15:17 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-10-01 15:17 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-01 15:31 UTC, dsavineau submitted a review, later dismissed

2020-10-01 15:31 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-01 15:31 UTC, guits commented
jenkins test centos-container-collocation

2020-10-01 15:31 UTC, guits commented
jenkins test centos-non_container-collocation

2020-10-02 14:36 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-02 15:00 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-03 06:26 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-03 12:02 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-04 20:40 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-10-04 21:40 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-10-04 21:40 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-04 21:48 UTC, guits commented
jenkins test centos-non_container-collocation

2020-10-04 21:48 UTC, guits commented
jenkins test centos-container-collocation

2020-10-04 21:49 UTC, guits commented
jenkins test centos-non_container-all_in_one

2020-10-04 21:49 UTC, guits commented
jenkins test centos-container-all_in_one

2020-10-05 14:50 UTC, dsavineau requested changes

2020-10-05 14:50 UTC, dsavineau commented on roles/ceph-rgw/tasks/pre_requisite.yml
> +    mode: "0400"
you can set `ceph` for owner/group as this code is only executed for non containerized deployment.

Also the mode on this key was `0600` and not `0400`

2020-10-05 14:50 UTC, dsavineau commented on roles/ceph-rgw/tasks/pre_requisite.yml
> +    - rgw_instances is defined
as far as I know rgw_instances is always defined since we call ceph-facts before ceph-handler

2020-10-05 14:50 UTC, dsavineau commented on roles/ceph-rgw/tasks/pre_requisite.yml
> +  when:
You need the `cephx` condition as before

2020-10-05 14:59 UTC, dsavineau requested changes

2020-10-05 14:59 UTC, dsavineau commented on roles/ceph-rgw/tasks/pre_requisite.yml
> +    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
This task is only for non containerized deployment so `ceph` is enough as owner and group value.

But you have to add a condition on the import_role call with `not containerized_deployment | bool`

2020-10-05 18:17 UTC, guits commented
jenkins test centos-container-all_in_one

2020-10-06 05:38 UTC, merged