[skip ci] ceph_pool: refact module
ceph/ceph-ansible pull request #5865
Opened 2020-09-28 21:28 UTC by guits

remove complexity about current defaults in running cluster

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-09-28 21:40 UTC, dsavineau requested changes

2020-09-28 21:40 UTC, dsavineau commented on roles/ceph-facts/tasks/facts.yml
> +    osd_pool_default_pg_num: "{{ ceph_conf_overrides.get('global', {}).get('osd_pool_default_pgp_num', ceph_osd_pool_default_pgp_num) }}"
osd_pool_default_**pgp**_num

2020-09-29 05:44 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-29 07:17 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-29 07:29 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-29 07:40 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-29 13:12 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-30 09:49 UTC, guits commented on library/ceph_pool.py
> +                rc, cmd, out, err = update_pool(module,
TODO: check whether there is an impact when running `update_pool()` in case of `delta` is empty after removing either `size`, `pg_num` or `pgp_num`

2020-09-30 12:18 UTC, guits commented
jenkins test centos-container-lvm_osds

2020-09-30 12:19 UTC, guits commented
jenkins test centos-container-lvm_batch

2020-09-30 12:31 UTC, guits commented
jenkins test centos-non_container-all_daemons

2020-09-30 12:32 UTC, guits commented
jenkins test centos-container-all_daemons

2020-09-30 12:32 UTC, guits commented
jenkins test centos-non_container-lvm_batch

2020-09-30 12:32 UTC, guits commented
jenkins test centos-non_container-lvm_osds

2020-09-30 15:22 UTC, guits commented
jenkins test centos-container-all_daemons

2020-10-02 05:42 UTC, merged