mon: delegate mon socket in-use check
ceph/ceph-ansible pull request #5947
Opened 2020-10-19 11:55 UTC by gaudenz

This check must be delegated to the mon host.

Signed-off-by: Gaudenz Steinlin <gaudenz.steinlin@cloudscale.ch>

2020-10-19 12:10 UTC, guits requested changes

2020-10-19 12:10 UTC, guits commented on roles/ceph-facts/tasks/facts.yml
> +      delegate_to: '{{ item.item }}'
you are adding a `delegate_to` while there's already one on this task

2020-10-19 12:27 UTC, guits commented
@gaudenz what's the goal of this PR given there's already a `delegate_to` on that task?

2020-10-29 14:56 UTC, gaudenz commented
Sorry for this. I initially developed this fix for the `stable-5.0` branch and as it cleanly applied to master I did not notice that the bug has already been fixed in master by commit 69f7e3538. This pull request is obsolete.

2020-10-29 14:56 UTC, closed without merging