Really use target_size_ratio in ceph_pool.py and rgw.
ceph/ceph-ansible pull request #6139
Opened 2020-12-15 07:20 UTC by Fbrachere

When creating a new pool, target_size_ratio is ignored by ansible module ceph_pool.py.
It's neither used in role ceph-rgw.
This PR fixes this 2 issues.

2020-12-15 08:27 UTC, guits commented
@Fbrachere you are missing a sign-off and a commit message.

2020-12-15 08:31 UTC, guits requested changes
please, add a sign off **and** a commit message

2020-12-15 09:37 UTC, guits approved these changes

2020-12-15 10:02 UTC, guits commented
jenkins test centos-non_container-purge

2020-12-15 10:40 UTC, guits commented
jenkins test centos-non_container-collocation

2020-12-15 14:44 UTC, dsavineau requested changes
I think you should add a test to reflect that change

https://github.com/ceph/ceph-ansible/blob/master/tests/library/test_ceph_pool.py

2020-12-16 06:43 UTC, Fbrachere commented
> I think you should add a test to reflect that change

Test added.

2020-12-16 09:07 UTC, Fbrachere commented
jenkins test centos-container-all_daemons

2020-12-16 09:08 UTC, Fbrachere commented
jenkins test centos-non_container-switch_to_containers

2020-12-16 14:09 UTC, guits approved these changes

2020-12-16 14:10 UTC, merged