[skip ci] fs2bs: skip migration when a mix of fs and bs is detected
ceph/ceph-ansible pull request #6143
Opened 2020-12-15 16:50 UTC by guits

wip

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1875777

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-12-16 10:51 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2020-12-16 10:51 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2020-12-16 12:53 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2020-12-18 07:43 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-11 19:44 UTC, guits commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +        container_run_cmd: "{{ container_binary + ' run --rm --privileged=true --net=host --pid=host --ipc=host -v /dev:/dev -v /etc/ceph:/etc/ceph -v /var/lib/ceph:/var/lib/ceph -v /var/run:/var/run
@dsavineau missing `:z` :sweat_smile: ?

2021-01-11 20:28 UTC, guits commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +        osd_ids: "{{ osd_ids | default([]) + [item] }}"
| union

2021-01-11 20:29 UTC, dsavineau requested changes

2021-01-11 20:29 UTC, dsavineau commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +        osd_ids: "{{ osd_ids | default([]) + [item] }}"
[item] -> item as it's already a list otherwise you will have list in a list

"children":[0,1,2]

2021-01-11 20:29 UTC, dsavineau commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +        - "{{ ((osd_tree.stdout | default('{}') | from_json).nodes | selectattr('name', 'match', inventory_hostname) | map(attribute='children') | list) }}"
inventory_hostname -> '^'+inventory_hostname+'$' to avoid multiple node matching

2021-01-11 20:29 UTC, dsavineau commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +        osd_ids: "{{ osd_ids | default([]) + [item] }}"
and union maggle

2021-01-12 09:51 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-12 09:51 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 12:33 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 13:15 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 13:15 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 15:04 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 15:10 UTC, dsavineau approved these changes

2021-01-12 15:42 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-12 19:40 UTC, merged