[skip ci] switch2container: fix mon quorum check
ceph/ceph-ansible pull request #6154
Opened 2020-12-18 10:01 UTC by guits

The current check makes no sense because it checks any of other monitor
than the one being played (either a previous one already converted or a
next that isn't yet converted) is present on the quorum.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1909011

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2020-12-18 10:08 UTC, guits commented
@dsavineau I even wonder if we really have to delegate this on another mon in fact.

2020-12-18 10:10 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2020-12-18 12:56 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2020-12-18 15:55 UTC, dsavineau commented
jenkins test centos-non_container-switch_to_containers

2021-01-08 04:54 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-01-08 13:40 UTC, dsavineau commented
jenkins test centos-non_container-switch_to_containers

2021-01-08 19:44 UTC, dsavineau requested changes
What is the reason for using `daemon mon.entity` instead of the current code ?

2021-01-08 19:44 UTC, dsavineau commented on infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
> +      command: "{{ container_binary }} run --rm  -v /etc/ceph:/etc/ceph -v /run/ceph:/run/ceph --entrypoint=ceph {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }} daemon
you need to add the `:z` flag to the bind mounts and readd the `cluster` variable

2021-01-11 12:34 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-01-11 12:34 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-01-11 13:38 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-01-11 16:29 UTC, dsavineau approved these changes

2021-01-11 19:41 UTC, dsavineau approved these changes

2021-01-11 19:42 UTC, merged