[skip ci] library: refact ceph_dashboard_user
ceph/ceph-ansible pull request #6169
Opened 2021-01-06 13:11 UTC by guits

refact this module due to recent changes in ceph pacific.
The password must be passed with `-i` option.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-01-06 13:11 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-06 13:11 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-06 13:16 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-06 13:17 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-06 13:33 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 09:01 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 09:24 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 11:47 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 11:47 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 13:05 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 13:05 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 13:12 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 13:12 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 13:18 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 13:18 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 13:51 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-01-07 13:51 UTC, guits commented
jenkins test centos-container-all_daemons

2021-01-07 16:20 UTC, dsavineau requested changes
if I remember correctly you also need to do the change for the ISCSI tasks (`iscsi-gateway-add`)

2021-01-07 16:20 UTC, dsavineau commented on module_utils/ca_common.py
> +    command_exec.extend([container_binary, 'run'])
I think you can simply do `command_exec = [container_binary, 'run']`

2021-01-07 16:20 UTC, dsavineau commented on roles/ceph-dashboard/tasks/configure_dashboard.yml
> +  command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} dashboard set-grafana-api-password -i -"
You need to also add the `--interactive` container option there I think (after `container_exec_cmd`)

2021-01-07 16:20 UTC, dsavineau commented on roles/ceph-dashboard/tasks/configure_dashboard.yml
> +      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} dashboard set-rgw-api-access-key -i -"
ditto

2021-01-07 16:20 UTC, dsavineau commented on roles/ceph-dashboard/tasks/configure_dashboard.yml
> +      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} dashboard set-rgw-api-secret-key -i -"
ditto

2021-01-07 18:38 UTC, guits commented
jenkins test centos-non_container-lvm_osds

2021-01-07 19:57 UTC, guits commented
jenkins test centos-non_container-lvm_osds

2021-01-07 20:02 UTC, dsavineau commented
jenkins test centos-non_container-purge

2021-01-07 22:09 UTC, dsavineau approved these changes

2021-01-07 22:09 UTC, merged