[skip ci] fs2bs: add missing options in container cli
ceph/ceph-ansible pull request #6178
Opened 2021-01-11 15:57 UTC by guits

This adds missing `:z` parameter in the bindmount options from the CLI
command built

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-01-11 16:08 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-11 16:08 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-11 16:29 UTC, dsavineau approved these changes

2021-01-27 14:23 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-27 14:23 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-27 14:26 UTC, dsavineau requested changes

2021-01-27 14:26 UTC, dsavineau commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +      command: "{{ container_binary + ' exec ceph-mon-' + hostvars[groups[mon_group_name][0]]['ansible_hostname'] if containerized_deployment | bool else '' }} ceph osd tree -f json"
the `{{ cluster }}` variable is missing

2021-01-27 14:41 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-27 14:41 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-27 14:49 UTC, dsavineau requested changes

2021-01-27 14:49 UTC, dsavineau commented on infrastructure-playbooks/filestore-to-bluestore.yml
> +      command: "{{ container_binary + ' exec ceph-mon-' + hostvars[groups[mon_group_name][0]]['ansible_hostname'] if containerized_deployment | bool else '' }} --cluster {{ ceph }} ceph osd tree -f j
almost correct :D you can do it maggle

2021-01-27 14:51 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-27 14:51 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-27 14:55 UTC, dsavineau requested changes
I just saw that `container_exec_cmd` is still used later in the playbook

2021-01-28 12:58 UTC, guits commented
jenkins test centos-container-filestore_to_bluestore

2021-01-28 12:58 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-28 14:02 UTC, dsavineau approved these changes

2021-01-28 14:03 UTC, dsavineau commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-28 14:33 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-28 15:06 UTC, guits commented
jenkins test centos-non_container-filestore_to_bluestore

2021-01-28 15:26 UTC, merged