[skip ci] tests:
ceph/ceph-ansible pull request #6233
Opened 2021-02-01 19:33 UTC by guits

wip

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-02-01 19:33 UTC, guits commented
jenkins test centos-non_container-purge

2021-02-01 19:33 UTC, guits commented
jenkins test centos-container-purge

2021-02-01 19:43 UTC, guits commented
jenkins test centos-container-purge

2021-02-01 19:43 UTC, guits commented
jenkins test centos-non_container-purge

2021-02-01 20:19 UTC, guits commented
jenkins test centos-non_container-purge

2021-02-01 20:19 UTC, guits commented
jenkins test centos-container-purge

2021-02-01 22:28 UTC, dsavineau requested changes

2021-02-01 22:28 UTC, dsavineau commented on tox.ini
> +  !lvm_batch-!lvm_auto_discovery: ansible-playbook -vv -i {changedir}/{env:INVENTORY} {toxinidir}/tests/functional/lvm_setup.yml --limit 'osds:!osd2'
we need this in the `[purge]` section too

https://github.com/ceph/ceph-ansible/blob/master/tox.ini#L60

2021-02-02 08:53 UTC, guits commented
jenkins test centos-container-purge

2021-02-02 08:53 UTC, guits commented
jenkins test centos-non_container-purge

2021-02-02 09:08 UTC, guits commented
jenkins test centos-non_container-purge

2021-02-02 13:40 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-02-02 13:40 UTC, guits commented
jenkins test centos-container-all_daemons

2021-02-02 14:30 UTC, dsavineau approved these changes

2021-02-02 16:24 UTC, merged