debian/uca: remove the handler notification (backport)
ceph/ceph-ansible pull request #6300
Opened 2021-02-25 15:58 UTC by mcv21

This is a cherry-pick of 0f8a61a3ae08cc3b3f2b91968764eeecb565aab6 with the merge conflict resolved.

The "update apt cache" in the ceph-handler role was never called and the
handler trigger after adding the uca repository doesn't exist at all.
Instead of using a handler for that we can just set the update_cache
parameter to true like the other apt_repository tasks.

Justification for commit to a stable branch: this change was already made in master, but stable-5.0 is broken because it isn't applied there - failure log extract:
```
2021-02-25 15:03:50,357 p=4824 u=mv3 n=ansible | TASK [ceph-common : include debian_uca_repository.yml] *************************
2021-02-25 15:03:50,358 p=4824 u=mv3 n=ansible | Thursday 25 February 2021  15:03:50 +0000 (0:00:00.067)       0:01:48.924 ***** 
2021-02-25 15:03:50,427 p=4824 u=mv3 n=ansible | included: /nfs/users/nfs_m/mv3/software/ceph-ansible/roles/ceph-common/tasks/installs/debian_uca_repository.yml for sto-t1-1
2021-02-25 15:03:50,477 p=4824 u=mv3 n=ansible | TASK [ceph-common : add ubuntu cloud archive key package] **********************
2021-02-25 15:03:50,477 p=4824 u=mv3 n=ansible | Thursday 25 February 2021  15:03:50 +0000 (0:00:00.119)       0:01:49.043 ***** 
2021-02-25 15:03:51,521 p=4824 u=mv3 n=ansible | ok: [sto-t1-1]
2021-02-25 15:03:51,571 p=4824 u=mv3 n=ansible | TASK [ceph-common : add ubuntu cloud archive repository] ***********************
2021-02-25 15:03:51,572 p=4824 u=mv3 n=ansible | Thursday 25 February 2021  15:03:51 +0000 (0:00:01.094)       0:01:50.137 ***** 
2021-02-25 15:03:52,218 p=4824 u=mv3 n=ansible | ERROR! The requested handler 'update apt cache if a repo was added' was not found in either the main handlers list nor in the listening handlers list
```

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>

2021-02-25 16:07 UTC, mcv21 commented
I think the syntax check "one or more commits isn't signed-off" must be a false positive - there's only 1 commit in this MR, and it most definitely is signed-off...

2021-02-25 16:15 UTC, mcv21 commented
```
++ grep -c Signed-off-by
+ test 1 -ne 2
+ echo 'One or more commits is/are missing a Signed-off-by. Add it with '\''git commit -s'\''.'
One or more commits is/are missing a Signed-off-by. Add it with 'git commit -s'.
```
I think that means the signed-off-by check is confused by having >1 Signed-off-by? I'm not sure that's the correct check to be making, but I can remove one or other if you want...

2021-03-02 05:27 UTC, guits commented
> ```
> ++ grep -c Signed-off-by
> + test 1 -ne 2
> + echo 'One or more commits is/are missing a Signed-off-by. Add it with '\''git commit -s'\''.'
> One or more commits is/are missing a Signed-off-by. Add it with 'git commit -s'.
> ```
> 
> I think that means the signed-off-by check is confused by having >1 Signed-off-by?

Yes, it is confused because there is more than 1 signed-off

> I'm not sure that's the correct check to be making, but I can remove one or other if you want...

Yes, it is a correct check IMO because only 1 signed-off should be present, in the case of multiple authors you should use the `Co-Authored-by` statement instead. By the way, this is a cherry-pick, so I don't see why we should add a signed-off/co-authored-by here.

We usually use mergify for creating backports but I see it has failed for this one so thanks for having caught it :+1:

2021-03-02 05:29 UTC, guits requested changes
please, leave the original signed-off only

2021-03-02 10:04 UTC, mcv21 commented
> please, leave the original signed-off only

Done :)

2021-03-03 12:17 UTC, guits commented
jenkins test centos-non_container-lvm_osds

2021-03-03 12:18 UTC, guits approved these changes

2021-03-03 12:19 UTC, guits commented
it should be backported into stable-4.0 as well

2021-03-03 13:30 UTC, guits commented
jenkins test centos-non_container-lvm_osds

2021-03-03 13:30 UTC, mcv21 commented
> it should be backported into stable-4.0 as well

I agree; would you like me to do that, or will the mergify infrastructure take care of it?

2021-03-03 13:49 UTC, guits commented
failure in `centos-non_container-lvm_osds` is unrelated to this patch and was fixed in stable-5.0

2021-03-03 13:50 UTC, guits commented
@mcv21 I'm unsure mergify will take care of creating the backport in stable-4.0 given this PR isn't created against the master branch but let's give it a try 🙂

2021-03-03 13:50 UTC, merged