core: Refactor code quality issues
ceph/ceph-ansible pull request #6367
Opened 2021-03-19 19:20 UTC by akshgpt7

## Description

Hey, I'm a Developer Outreach at [DeepSource](https://deepsource.io/) and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality and performance improvements](https://deepsource.io/gh/akshgpt7/ceph-ansible/) to consider.

This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)

## Summary of changes
- Use literals instead of function calls to create data structure.
- Refactor unnecessary list comprehension.
- Simplify `if` statement.
- Refactor useless `else` block in the loop.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

2021-03-22 08:44 UTC, guits commented
Hi @akshgpt7 

Interesting patch, thanks for this contribution.

Do you mind adding a commit message and a sign-off to your commit please?

Thanks!

2021-03-22 09:36 UTC, akshgpt7 commented
Thanks @guits, I've added a commit message, and signed it off.

2021-03-23 08:15 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-03-23 08:15 UTC, guits commented
jenkins test centos-non_container-collocation

2021-03-23 08:15 UTC, guits commented
jenkins test centos-non_container-all_in_one

2021-03-23 08:15 UTC, guits commented
jenkins test centos-non_container-purge

2021-03-23 08:15 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-03-24 07:05 UTC, guits commented
@akshgpt7 FYI, i've fixed the few conflicts

2021-03-24 07:06 UTC, guits requested changes

2021-03-24 07:06 UTC, guits commented on plugins/actions/config_template.py
> +
```suggestion
```

2021-03-24 07:06 UTC, guits commented on plugins/actions/config_template.py
> +
```suggestion
```

2021-03-24 07:37 UTC, guits approved these changes

2021-03-24 12:48 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-03-24 12:48 UTC, guits commented
jenkins test centos-container-all_in_one

2021-03-24 14:45 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-03-24 17:33 UTC, akshgpt7 commented
@guits Is there anything else that needs to be done from my side?

2021-03-24 20:37 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-03-24 20:37 UTC, guits commented
> @guits Is there anything else that needs to be done from my side?

no, so failure we are seeing are not related to your patch, I'm working on fixing the ci

2021-03-25 13:57 UTC, merged

2021-03-25 18:07 UTC, akshgpt7 commented
@guits Thanks for merging this. I'd just like to inform you that the issues fixed here were detected by running DeepSource analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug risks on the fly for every change made. You can also use the Autofix feature to fix them with one click.
The `.deepsource.toml` file you merged will only take effect if you activate analysis for this repo.

Here's what you can do if you wish to activate DeepSource to continuously analyze your repository:
- [Sign up](https://deepsource.io/signup) on DeepSource and activate analysis for this repository.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings (this PR already added that, but feel free to edit it anytime).
- Track/Check analysis [here](https://deepsource.io/gh/ceph/ceph-ansible/).

If you have any doubts or questions, you can check out the [docs](https://deepsource.io/docs/), or feel free to reach out :)

2021-04-05 23:00 UTC, akshgpt7 commented
@guits do you need any help with activating DeepSource?
I ask so because the `.deepsource.toml` file that you merged will only take effect if analysis is activated.