[skip ci] dashboard: remove "certificate is valid for" error
ceph/ceph-ansible pull request #6680
Opened 2021-07-06 12:50 UTC by guits

When deploying dashboard with ssl certificates generated by
ceph-ansible, we enforce the CN to 'ceph-dashboard' which can makes
application such alertmanager complain like following:

`err="Post https://mgr0:8443/api/prometheus_receiver: x509: certificate is valid for ceph-dashboard, not mgr0" context_err="context deadline exceeded"`

The idea here is to add alternative names matching all mgr/mon instances
in the certificate so this error won't appear in logs.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1978869

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-07-06 12:53 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-06 12:53 UTC, guits commented
jenkins test centos-container-all_daemons

2021-07-06 13:15 UTC, guits commented
jenkins test centos-container-all_daemons

2021-07-06 13:15 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-06 15:49 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-06 17:52 UTC, dsavineau requested changes

2021-07-06 17:52 UTC, dsavineau commented on roles/ceph-dashboard/tasks/configure_dashboard.yml
> +    dashboard_server_addr: "{{ hostvars[item]['ansible_facts']['all_ipv4_addresses'] | ips_in_ranges(dashboard_network.split(',')) | first }}"
```suggestion
    dashboard_server_addr: "{{ ansible_facts['all_ipv4_addresses'] | ips_in_ranges(dashboard_network.split(',')) | first }}"
```

2021-07-06 17:52 UTC, dsavineau commented on roles/ceph-dashboard/tasks/configure_dashboard.yml
> +    dashboard_server_addr: "{{ hostvars[item]['ansible_facts']['all_ipv6_addresses'] | ips_in_ranges(dashboard_network.split(',')) | last }}"
ditto

2021-07-06 20:56 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-07 08:18 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-07 08:18 UTC, guits commented
jenkins test centos-container-all_daemons

2021-07-07 08:38 UTC, guits commented
jenkins test centos-container-all_daemons

2021-07-07 08:38 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-07-07 13:38 UTC, dsavineau approved these changes

2021-07-07 13:38 UTC, merged