[skip ci] update: convert straw bucket
ceph/ceph-ansible pull request #6689
Opened 2021-07-08 20:55 UTC by guits

After an upgrade, the presence of straw buckets will produce the
following warning (HEALTH_WARN):

```
crush map has legacy tunables (require firefly, min is hammer)
```

because straw bucket is a firefly feature it needs to be converted to
straw2.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967964

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-07-08 20:56 UTC, guits commented
jenkins test centos-non_container-update

2021-07-08 20:56 UTC, guits commented
jenkins test centos-container-update

2021-07-08 21:11 UTC, dsavineau commented on infrastructure-playbooks/rolling_update.yml
> +        ceph_cmd: "{{ hostvars[groups[mon_group_name][0]]['container_binary'] + ' run --rm --net=host -v /etc/ceph:/etc/ceph:z --entrypoint=ceph ' + ceph_docker_registry + '/' + ceph_docker_image + '
No need to import_role ceph-default and ceph-facts (tasks_from container_binary.yml) here ?

2021-07-08 21:32 UTC, guits commented
jenkins test centos-non_container-update

2021-07-08 21:32 UTC, guits commented
jenkins test centos-container-update

2021-07-08 21:42 UTC, dsavineau requested changes

2021-07-08 21:42 UTC, dsavineau commented on infrastructure-playbooks/rolling_update.yml
> +        ceph_cmd: "{{ hostvars[groups[mon_group_name][0]]['container_binary'] + ' run --rm --net=host -v /etc/ceph:/etc/ceph:z --entrypoint=ceph ' + ceph_docker_registry + '/' + ceph_docker_image + '
```suggestion
        ceph_cmd: "{{ container_binary + ' run --rm --net=host -v /etc/ceph:/etc/ceph:z --entrypoint=ceph ' + ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else 'ceph' }}"
```

2021-07-08 22:03 UTC, guits commented
jenkins test centos-container-update

2021-07-08 22:03 UTC, guits commented
jenkins test centos-non_container-update

2021-07-09 05:14 UTC, guits commented
jenkins test centos-container-update

2021-07-09 06:28 UTC, merged