cephadm-adopt: use ansible_user for ssh user
ceph/ceph-ansible pull request #6768
Opened 2021-07-27 17:45 UTC by clwluvw

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

2021-07-27 18:11 UTC, dsavineau reviewed
I'm not sure about this change. This will change the default workflow for most users.

I'm rather incline to add a new variable (like cephadm_ssh_user) with root as a default value and users can override this instead of relying on the `ansible_user` fact.

2021-07-27 18:11 UTC, dsavineau commented
jenkins test centos-container-cephadm_adopt

2021-07-27 21:09 UTC, clwluvw commented
> I'm not sure about this change. This will change the default workflow for most users.
> 
> I'm rather incline to add a new variable (like cephadm_ssh_user) with root as a default value and users can override this instead of relying on the `ansible_user` fact.

@dsavineau Makes sense. Done.

2021-07-28 05:38 UTC, guits commented
jenkins test centos-container-cephadm_adopt

2021-07-28 12:09 UTC, guits requested changes
just a few cosmetic changes.
also, could you add a (brief) commit message please?

Thanks!

2021-07-28 12:09 UTC, guits commented on infrastructure-playbooks/cephadm-adopt.yml
> +        user: "{{ cephadm_ssh_user|default('root') }}"
```suggestion
        user: "{{ cephadm_ssh_user | default('root') }}"
```

2021-07-28 12:09 UTC, guits commented on infrastructure-playbooks/cephadm-adopt.yml
> +    - name: allow cephadm key for {{ cephadm_ssh_user|default('root') }} account
```suggestion
    - name: allow cephadm key for {{ cephadm_ssh_user | default('root') }} account
```

2021-07-28 12:09 UTC, guits commented on infrastructure-playbooks/cephadm-adopt.yml
> +      command: "{{ ceph_cmd }} cephadm set-user {{ cephadm_ssh_user|default('root') }}"
```suggestion
    - name: set cpehadm ssh user to {{ cephadm_ssh_user | default('root') }}
      command: "{{ ceph_cmd }} cephadm set-user {{ cephadm_ssh_user | default('root') }}"
```

2021-07-28 12:09 UTC, guits commented on infrastructure-playbooks/cephadm-adopt.yml
> +      delegate_to: '{{ groups[mon_group_name][0] }}'
```suggestion
      delegate_to: "{{ groups[mon_group_name][0] }}"
```

2021-07-28 12:09 UTC, guits commented on infrastructure-playbooks/cephadm-adopt.yml
> +    - name: set cpehadm ssh user to {{ cephadm_ssh_user|default('root') }}
```suggestion
    - name: set cephadm ssh user to {{ cephadm_ssh_user|default('root') }}
```

2021-07-28 12:22 UTC, clwluvw commented
@guits Done.

2021-08-04 07:15 UTC, guits commented
jenkins test centos-container-cephadm_adopt

2021-08-04 07:16 UTC, guits approved these changes

2021-08-13 23:55 UTC, clwluvw commented
jenkins test centos-container-cephadm_adopt

2021-08-18 07:10 UTC, merged

2021-08-18 08:40 UTC, clwluvw commented
@guits Can it be backported too?

2021-09-09 07:25 UTC, clwluvw commented
ping @guits

2021-09-09 12:07 UTC, clwluvw commented
@Mergifyio backport stable-6.0

2021-09-09 12:07 UTC, clwluvw commented
@Mergifyio backport stable-5.0