common: do not log keyring secret
ceph/ceph-ansible pull request #6808
Opened 2021-08-09 14:02 UTC by guits

let's not display any keyring secret by default in ansible log.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1980744

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-08-09 15:05 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-09 15:05 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-09 15:05 UTC, guits commented
jenkins test centos-container-lvm_osds

2021-08-09 16:00 UTC, dsavineau requested changes

2021-08-09 16:00 UTC, dsavineau commented on roles/ceph-nfs/tasks/pre_requisite_non_container.yml
> +            no_log: "{{ no_log_on_ceph_key_tasks }}"
```suggestion
          no_log: "{{ no_log_on_ceph_key_tasks }}"
```

2021-08-10 08:01 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-10 08:01 UTC, guits commented
jenkins test centos-non_container-collocation

2021-08-10 13:37 UTC, dsavineau approved these changes

2021-08-10 13:39 UTC, dsavineau commented
jenkins test centos-non_container-collocation

2021-08-10 13:39 UTC, dsavineau commented
jenkins test centos-non_container-all_daemons

2021-08-10 14:57 UTC, dsavineau commented
jenkins test centos-non_container-collocation

2021-08-11 15:33 UTC, merged