[skip ci] containers: introduce target systemd unit
ceph/ceph-ansible pull request #6818
Opened 2021-08-11 07:22 UTC by guits

This adds ceph-*.target systemd unit files support for containerized
deployments.
This also fixes a regression introduced by PR #6719 (rgw and nfs systemd
units not getting purged)

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1962748

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-08-11 08:51 UTC, guits commented
jenkins test centos-container-lvm_osds

2021-08-11 08:51 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-11 08:51 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-12 16:24 UTC, guits commented
jenkins test centos-container-collocation

2021-08-12 16:26 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-12 16:26 UTC, guits commented
jenkins test centos-container-all_in_one

2021-08-12 16:27 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-12 16:27 UTC, guits commented
jenkins test centos-non_container-collocation

2021-08-12 16:27 UTC, guits commented
jenkins test centos-non_container-switch_to_containers

2021-08-12 23:05 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-12 23:05 UTC, guits commented
jenkins test centos-non_container-all_daemons

2021-08-12 23:05 UTC, guits commented
jenkins test centos-non_container-collocation

2021-08-13 05:54 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-16 12:26 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-16 13:11 UTC, dsavineau approved these changes

2021-08-16 14:16 UTC, guits commented
jenkins test centos-container-all_daemons

2021-08-16 18:16 UTC, dsavineau approved these changes

2021-08-17 01:08 UTC, dsavineau requested changes

2021-08-17 01:08 UTC, dsavineau commented on infrastructure-playbooks/cephadm-adopt.yml
>          name: ceph-rgw.target
```suggestion
        name: ceph-radosgw.target
```

I think that's a typo

```console
TASK [stop and disable ceph-radosgw systemd target] ******************************************************************************************************************************************************************************************
task path: /home/dim/ceph-ansible/infrastructure-playbooks/cephadm-adopt.yml:786
Tuesday 17 August 2021  00:53:17 +0200 (0:00:02.570)       0:10:45.285 ********
fatal: [rgw0]: FAILED! => changed=false 
  msg: 'Could not find the requested service ceph-rgw.target: host'
```

2021-08-17 19:51 UTC, dsavineau requested changes
only for idempotency purpose...

2021-08-17 19:51 UTC, dsavineau commented on infrastructure-playbooks/cephadm-adopt.yml
>          enabled: false
```suggestion
        enabled: false
      failed_when: false
```

2021-08-17 19:51 UTC, dsavineau commented on infrastructure-playbooks/cephadm-adopt.yml
>          enabled: false
```suggestion
        enabled: false
      failed_when: false
```

2021-08-17 19:51 UTC, dsavineau commented on infrastructure-playbooks/cephadm-adopt.yml
>          enabled: false
```suggestion
        enabled: false
      failed_when: false
```

2021-08-18 15:00 UTC, dsavineau approved these changes

2021-08-18 15:08 UTC, merged